# Default values for Watston Assistance Instance Cr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: wa
cpd_namespace: gitops-cp4d-instance
version: "4.0.8"
storage_class: portworx-watson-assistant-sc
syncWave: "-3"
